wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    code_path: code/run_apl.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    t:
      1:
      - 1
      4: 3.6.10
      5: 0.10.32
      8:
      - 5
apl:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1000
cuda:
  desc: null
  value: false
epochs:
  desc: null
  value: 3
load:
  desc: null
  value: ''
lr:
  desc: null
  value: 0.1
note:
  desc: null
  value: ''
save_freq:
  desc: null
  value: 100
train:
  desc: null
  value: false
